### ISSUE TITLE
LaCrosse TX141W not received anymore after 1.4 to 1.5 upgrade

### ISSUE THREAD

**Issue by hb9eue** [1technophile/OpenMQTTGateway#1598] opened 2023-04-07 13:16 UTC
Hi

Thank you for this wonderfully usefull gateway.

Since I upgraded to 1.5 on a HellTec Lora V2 board, my TFA (LaCrosse TX141W Protocoll) outdoor weater station is not being heard (probably not decoded) anymore.

Other rtl_433 sensors (which I would rather love to filter out) are still being received.

Thanks for looking into this.
-Benoît-

**Comment by NorthernMan54** [comment] 2023-04-12 21:25
We are looking into this, and a couple of other sensors.  Stay tuned

PS I have one of these as well, so I need it to work

**Comment by NorthernMan54** [comment] 2023-04-19 00:51
We have identified the issue, and this is a duplicate of #1609

**Closed as completed by NorthernMan54** 2023-04-19 00:51 UTC
